#!/usr/bin/perl-w
	
use Tk;
use Tk::BrowseEntry;


#necessary for load pall packages
use FindBin;
use lib "$FindBin::Bin/../";
use PackagesLib;

use Genesis;
use aliased 'Packages::InCAM::InCAM';
use aliased 'Helpers::GeneralHelper';

unless ($ENV{JOB}) {
	$jobName = shift;
#	$stepName = shift;
} else {
	$jobName = "$ENV{JOB}";
#	$stepName = "panel";
}
my $genesis = Genesis->new();
$adjustDrill = 'vrtane';

$genesis->INFO(units=>'mm',entity_type => 'layer',entity_path => "$jobName/o+1/f",data_type => 'NUM_TOOL');
	$pocetTool = $genesis->{doinfo}{gNUM_TOOL}; 


	$genesis->INFO(units=>'mm',entity_type => 'layer',entity_path => "$jobName/o+1/f",data_type => 'TOOL');
	@numVrtaku = @{$genesis->{doinfo}{gTOOLnum}};
	@finishSize = @{$genesis->{doinfo}{gTOOLfinish_size}};
	@type = @{$genesis->{doinfo}{gTOOLtype}};
	@type2 = @{$genesis->{doinfo}{gTOOLtype2}};
	@min_tools = @{$genesis->{doinfo}{gTOOLmin_tol}};
	@max_tools = @{$genesis->{doinfo}{gTOOLmax_tol}};
	@shape = @{$genesis->{doinfo}{gTOOLshape}};
	
    $genesis -> COM('tools_tab_reset');
$pocetTool -= 1;
for($countDrill = 0;$countDrill <= $pocetTool;$countDrill++) {

	
		if ($type[$countDrill] eq "plated") {
			$type[$countDrill] = "plate";
		}elsif ($type[$countDrill] eq "non_plated") {
			$type[$countDrill] = "nplate";
		}
		if ($shape[$countDrill]	eq 'hole') {
				$drill_size = $genesis -> COM('drill_size_hook',layer=>'f',thickness=>'0',user_params=>"$adjustDrill",finish_size=>"$finishSize[$countDrill]",bit=>'Drill Des',type=>"$type[$countDrill]",min_tol=>"$min_tools[$countDrill]",max_tol=>"$max_tools[$countDrill]");
				@drill_size_bit = split /\s+/,$drill_size;
				$genesis -> COM('tools_tab_add',num=>"$numVrtaku[$countDrill]",type=>"$type[$countDrill]",type2=>"$type2[$countDrill]",min_tol=>"$min_tools[$countDrill]",max_tol=>"$max_tools[$countDrill]",bit=>"$drill_size_bit[1]",finish_size=>"$finishSize[$countDrill]",drill_size=>"$drill_size_bit[0]");
		}

}
$genesis -> COM('tools_set',layer=>'f',thickness=>'0',user_params=>"$adjustDrill",slots=>'yes');
