#!/usr/bin/perl-w
 
use Tk;
use sqlNoris;


use lib qw( C:\Perl\site\lib\TpvScripts\Scripts );

use aliased 'Helpers::GeneralHelper';
use aliased 'Enums::EnumsDrill';
use aliased 'Packages::Other::CustomerNote';
use aliased 'Connectors::HeliosConnector::HegMethods';
use aliased 'Packages::InCAM::InCAM';

use aliased 'CamHelpers::CamDTM';


my $inCAM = InCAM->new();

CalculationDrills("$ENV{JOB}");


sub CalculationDrills {
	my $jobName = shift;
	
	my $customer = HegMethods->GetCustomerInfo($jobName);
	my $note = CustomerNote->new( $customer->{"reference_subjektu"} );
	

		if (HegMethods->GetTypeOfPcb($jobName) eq 'Jednostranny') {
					_SetDrill(EnumsDrill->DTM_VRTANE, $jobName);
			
		}elsif($note->PlatedHolesType() ne undef){
				# Vraci tri hodnoty
				#- undef
				# EnumsDrill->DTM_VYSLEDNE
				# EnumsDrill->DTM_VRTANE
				my $usrHolesType = $note->PlatedHolesType();
				_SetDrill($usrHolesType, $jobName);
		}else{
			_Gui($jobName);
		}
}
# GUI ###################################
sub _Gui {
		my $jobId = shift;
		
		my $logo_way = GeneralHelper->Root()."\\_from_z\\drill.gif";
		$main = MainWindow->new;
		$main->title('Vys/Vrt Job =>' . $jobId);
		$main->minsize(qw(260 50));

			$subMain = $main->Frame(-width=>100, -height=>50)->pack(-side=>'top');
				$left = $subMain->Frame(-width=>100, -height=>50)->pack(-side=>'left', -fill=>'both');
						$logomain = $left->Frame(-width=>100, -height=>50)->pack(-side=>'left', -fill=>'both');
								$logo_frame = $logomain->Frame(-width=>50, -height=>50)->pack(-side=>'left');
									$error_logo = $logo_frame->Photo(-file=>"$logo_way");
									$logo_frame->Label(-image=>$error_logo)->pack(); 
						
				$right = $subMain->Frame(-width=>100, -height=>50)->pack(-side=>'right');
						$subRightTop = $right->Frame(-width=>100, -height=>25)->pack(-side=>'top',-fill=>'both');
									$subRightTop->Radiobutton(-value=>"vysledne", -variable=>\$adjust, -text=>"vysledne",-font=>'arial 12 {bold}')->pack(-side=>'left',-padx => 5, -pady => 5);
						$subRightBot = $right->Frame(-width=>100, -height=>25)->pack(-side=>'top',-fill=>'both');
									$subRightBot->Radiobutton(-value=>"vrtane", -variable=>\$adjust, -text=>"vrtane",-font=>'arial 12 {bold}')->pack(-side=>'left',-padx => 5, -pady => 5);
			
			$bottom = $main->Frame(-width=>100, -height=>50)->pack(-side=>'bottom', -fill=>'both');
						$bottom->Button(-height => "3", -text => "Pokracovat",-command=> sub {_SetDrill($adjust, $jobId)},-bg=>'grey',-relief=>'raise',-bd=>'3')->pack(-padx => 5, -pady => 5,-side=>'bottom', -fill=>'both');
			
			
		MainLoop ();
}

sub _SetDrill {
      my $adjustDrill = shift;
      my $jobId       = shift;

      # nacte nastroje
      my @tools = CamDTM->GetDTMTools( $inCAM, $jobId, "o+1", "m" );

      # 1) Reset DTM (vymazani),
      # 2) Nastaveni vysledne/vrtane
      # 3) Pridani nastroju do DTM + recalculate tools by drill_size_hook
      my $recalc = 1; # recalculate tools = yes
      CamDTM->SetDTMTools( $inCAM, $jobId, "o+1", "m", \@tools, $adjustDrill, $recalc );


exit;
}