#!/bin/csh
set echo

set system_os = `uname`

if ( $system_os =~ *"NT" ) then
   alias awk gawk 
endif


set INFO = $INCAM_TMP/info
alias DO_INFO 'COM info,out_file=$INFO,write_mode=replace,units=mm,args=\!:*;source $INFO;rm $INFO'


	DO_INFO -t job -e $JOB -d ATTR
	set i = 1
	set material_table = FR4
 	while ($i <= $#gATTRname)
		if ($gATTRname[$i] == material) then
			set material_table = $gATTRval[$i]
			break
		endif
		@ i ++
	end

echo $material_table

set ncTOOL_SIZE2 = .1000


set ncTOOL_SIZE_mic = `echo "$ncTOOL_SIZE2" | awk95 '{printf ("%6.2f", $1 )}'`


set TOOL_SIZE = `cat $INCAM_SERVER/site_data/hooks/ncd/parametersFile/$material_table | grep C${ncTOOL_SIZE_mic}F | cut -d "F" -f2`

echo VVVVVVVVVVVVV $TOOL_SIZE

#EOF
