
package Connectors::HeliosConnector::MyElements::GetInfo;
use strict;
use warnings;

{ # BLOCK to scope variables

sub get_xmlns { 'http://lcs.cz/webservices/' }

__PACKAGE__->__set_name('GetInfo');
__PACKAGE__->__set_nillable();
__PACKAGE__->__set_minOccurs();
__PACKAGE__->__set_maxOccurs();
__PACKAGE__->__set_ref();

use base qw(
    SOAP::WSDL::XSD::Typelib::Element
    SOAP::WSDL::XSD::Typelib::ComplexType
);

our $XML_ATTRIBUTE_CLASS;
undef $XML_ATTRIBUTE_CLASS;

sub __get_attr_class {
    return $XML_ATTRIBUTE_CLASS;
}

use Class::Std::Fast::Storable constructor => 'none';
use base qw(SOAP::WSDL::XSD::Typelib::ComplexType);

Class::Std::initialize();

{ # BLOCK to scope variables

my %myCode_of :ATTR(:get<myCode>);
my %myValue_of :ATTR(:get<myValue>);

__PACKAGE__->_factory(
    [ qw(        myCode
        myValue

    ) ],
    {
        'myCode' => \%myCode_of,
        'myValue' => \%myValue_of,
    },
    {
        'myCode' => 'SOAP::WSDL::XSD::Typelib::Builtin::string',
        'myValue' => 'SOAP::WSDL::XSD::Typelib::Builtin::string',
    },
    {

        'myCode' => 'myCode',
        'myValue' => 'myValue',
    }
);

} # end BLOCK






} # end of BLOCK



1;


=pod

=head1 NAME

MyElements::GetInfo

=head1 DESCRIPTION

Perl data type class for the XML Schema defined element
GetInfo from the namespace http://lcs.cz/webservices/.







=head1 PROPERTIES

The following properties may be accessed using get_PROPERTY / set_PROPERTY
methods:

=over

=item * myCode

 $element->set_myCode($data);
 $element->get_myCode();




=item * myValue

 $element->set_myValue($data);
 $element->get_myValue();





=back


=head1 METHODS

=head2 new

 my $element = MyElements::GetInfo->new($data);

Constructor. The following data structure may be passed to new():

 {
   myCode =>  $some_value, # string
   myValue =>  $some_value, # string
 },

=head1 AUTHOR

Generated by SOAP::WSDL

=cut

