
package Connectors::HeliosConnector::MyElements::GetInfoResponse;
use strict;
use warnings;

{ # BLOCK to scope variables

sub get_xmlns { 'http://lcs.cz/webservices/' }

__PACKAGE__->__set_name('GetInfoResponse');
__PACKAGE__->__set_nillable();
__PACKAGE__->__set_minOccurs();
__PACKAGE__->__set_maxOccurs();
__PACKAGE__->__set_ref();

use base qw(
    SOAP::WSDL::XSD::Typelib::Element
    SOAP::WSDL::XSD::Typelib::ComplexType
);

our $XML_ATTRIBUTE_CLASS;
undef $XML_ATTRIBUTE_CLASS;

sub __get_attr_class {
    return $XML_ATTRIBUTE_CLASS;
}

use Class::Std::Fast::Storable constructor => 'none';
use base qw(SOAP::WSDL::XSD::Typelib::ComplexType);

Class::Std::initialize();

{ # BLOCK to scope variables

my %GetInfoResult_of :ATTR(:get<GetInfoResult>);

__PACKAGE__->_factory(
    [ qw(        GetInfoResult

    ) ],
    {
        'GetInfoResult' => \%GetInfoResult_of,
    },
    {
        'GetInfoResult' => 'SOAP::WSDL::XSD::Typelib::Builtin::string',
    },
    {

        'GetInfoResult' => 'GetInfoResult',
    }
);

} # end BLOCK






} # end of BLOCK



1;


=pod

=head1 NAME

MyElements::GetInfoResponse

=head1 DESCRIPTION

Perl data type class for the XML Schema defined element
GetInfoResponse from the namespace http://lcs.cz/webservices/.







=head1 PROPERTIES

The following properties may be accessed using get_PROPERTY / set_PROPERTY
methods:

=over

=item * GetInfoResult

 $element->set_GetInfoResult($data);
 $element->get_GetInfoResult();





=back


=head1 METHODS

=head2 new

 my $element = MyElements::GetInfoResponse->new($data);

Constructor. The following data structure may be passed to new():

 {
   GetInfoResult =>  $some_value, # string
 },

=head1 AUTHOR

Generated by SOAP::WSDL

=cut

