
package Connectors::HeliosConnector::MyElements::KeepAlive;
use strict;
use warnings;

{ # BLOCK to scope variables

sub get_xmlns { 'http://lcs.cz/webservices/' }

__PACKAGE__->__set_name('KeepAlive');
__PACKAGE__->__set_nillable();
__PACKAGE__->__set_minOccurs();
__PACKAGE__->__set_maxOccurs();
__PACKAGE__->__set_ref();

use base qw(
    SOAP::WSDL::XSD::Typelib::Element
    SOAP::WSDL::XSD::Typelib::ComplexType
);

our $XML_ATTRIBUTE_CLASS;
undef $XML_ATTRIBUTE_CLASS;

sub __get_attr_class {
    return $XML_ATTRIBUTE_CLASS;
}

use Class::Std::Fast::Storable constructor => 'none';
use base qw(SOAP::WSDL::XSD::Typelib::ComplexType);

Class::Std::initialize();

{ # BLOCK to scope variables

my %sessionToken_of :ATTR(:get<sessionToken>);

__PACKAGE__->_factory(
    [ qw(        sessionToken

    ) ],
    {
        'sessionToken' => \%sessionToken_of,
    },
    {
        'sessionToken' => 'SOAP::WSDL::XSD::Typelib::Builtin::string',
    },
    {

        'sessionToken' => 'sessionToken',
    }
);

} # end BLOCK






} # end of BLOCK



1;


=pod

=head1 NAME

MyElements::KeepAlive

=head1 DESCRIPTION

Perl data type class for the XML Schema defined element
KeepAlive from the namespace http://lcs.cz/webservices/.







=head1 PROPERTIES

The following properties may be accessed using get_PROPERTY / set_PROPERTY
methods:

=over

=item * sessionToken

 $element->set_sessionToken($data);
 $element->get_sessionToken();





=back


=head1 METHODS

=head2 new

 my $element = MyElements::KeepAlive->new($data);

Constructor. The following data structure may be passed to new():

 {
   sessionToken =>  $some_value, # string
 },

=head1 AUTHOR

Generated by SOAP::WSDL

=cut

