
package Connectors::HeliosConnector::MyElements::LogOnResponse;
use strict;
use warnings;

{ # BLOCK to scope variables

sub get_xmlns { 'http://lcs.cz/webservices/' }

__PACKAGE__->__set_name('LogOnResponse');
__PACKAGE__->__set_nillable();
__PACKAGE__->__set_minOccurs();
__PACKAGE__->__set_maxOccurs();
__PACKAGE__->__set_ref();

use base qw(
    SOAP::WSDL::XSD::Typelib::Element
    SOAP::WSDL::XSD::Typelib::ComplexType
);

our $XML_ATTRIBUTE_CLASS;
undef $XML_ATTRIBUTE_CLASS;

sub __get_attr_class {
    return $XML_ATTRIBUTE_CLASS;
}

use Class::Std::Fast::Storable constructor => 'none';
use base qw(SOAP::WSDL::XSD::Typelib::ComplexType);

Class::Std::initialize();

{ # BLOCK to scope variables

my %LogOnResult_of :ATTR(:get<LogOnResult>);

__PACKAGE__->_factory(
    [ qw(        LogOnResult

    ) ],
    {
        'LogOnResult' => \%LogOnResult_of,
    },
    {
        'LogOnResult' => 'SOAP::WSDL::XSD::Typelib::Builtin::string',
    },
    {

        'LogOnResult' => 'LogOnResult',
    }
);

} # end BLOCK






} # end of BLOCK



1;


=pod

=head1 NAME

MyElements::LogOnResponse

=head1 DESCRIPTION

Perl data type class for the XML Schema defined element
LogOnResponse from the namespace http://lcs.cz/webservices/.







=head1 PROPERTIES

The following properties may be accessed using get_PROPERTY / set_PROPERTY
methods:

=over

=item * LogOnResult

 $element->set_LogOnResult($data);
 $element->get_LogOnResult();





=back


=head1 METHODS

=head2 new

 my $element = MyElements::LogOnResponse->new($data);

Constructor. The following data structure may be passed to new():

 {
   LogOnResult =>  $some_value, # string
 },

=head1 AUTHOR

Generated by SOAP::WSDL

=cut

