
package Connectors::HeliosConnector::MyElements::LogOffResponse;
use strict;
use warnings;

{ # BLOCK to scope variables

sub get_xmlns { 'http://lcs.cz/webservices/' }

__PACKAGE__->__set_name('LogOffResponse');
__PACKAGE__->__set_nillable();
__PACKAGE__->__set_minOccurs();
__PACKAGE__->__set_maxOccurs();
__PACKAGE__->__set_ref();

use base qw(
    SOAP::WSDL::XSD::Typelib::Element
    SOAP::WSDL::XSD::Typelib::ComplexType
);

our $XML_ATTRIBUTE_CLASS;
undef $XML_ATTRIBUTE_CLASS;

sub __get_attr_class {
    return $XML_ATTRIBUTE_CLASS;
}

use Class::Std::Fast::Storable constructor => 'none';
use base qw(SOAP::WSDL::XSD::Typelib::ComplexType);

Class::Std::initialize();

{ # BLOCK to scope variables

my %LogOffResult_of :ATTR(:get<LogOffResult>);

__PACKAGE__->_factory(
    [ qw(        LogOffResult

    ) ],
    {
        'LogOffResult' => \%LogOffResult_of,
    },
    {
        'LogOffResult' => 'SOAP::WSDL::XSD::Typelib::Builtin::string',
    },
    {

        'LogOffResult' => 'LogOffResult',
    }
);

} # end BLOCK






} # end of BLOCK



1;


=pod

=head1 NAME

MyElements::LogOffResponse

=head1 DESCRIPTION

Perl data type class for the XML Schema defined element
LogOffResponse from the namespace http://lcs.cz/webservices/.







=head1 PROPERTIES

The following properties may be accessed using get_PROPERTY / set_PROPERTY
methods:

=over

=item * LogOffResult

 $element->set_LogOffResult($data);
 $element->get_LogOffResult();





=back


=head1 METHODS

=head2 new

 my $element = MyElements::LogOffResponse->new($data);

Constructor. The following data structure may be passed to new():

 {
   LogOffResult =>  $some_value, # string
 },

=head1 AUTHOR

Generated by SOAP::WSDL

=cut

