
package Connectors::HeliosConnector::MyElements::ProcessXmlResponse;
use strict;
use warnings;

{ # BLOCK to scope variables

sub get_xmlns { 'http://lcs.cz/webservices/' }

__PACKAGE__->__set_name('ProcessXmlResponse');
__PACKAGE__->__set_nillable();
__PACKAGE__->__set_minOccurs();
__PACKAGE__->__set_maxOccurs();
__PACKAGE__->__set_ref();

use base qw(
    SOAP::WSDL::XSD::Typelib::Element
    SOAP::WSDL::XSD::Typelib::ComplexType
);

our $XML_ATTRIBUTE_CLASS;
undef $XML_ATTRIBUTE_CLASS;

sub __get_attr_class {
    return $XML_ATTRIBUTE_CLASS;
}

use Class::Std::Fast::Storable constructor => 'none';
use base qw(SOAP::WSDL::XSD::Typelib::ComplexType);

Class::Std::initialize();

{ # BLOCK to scope variables

my %ProcessXmlResult_of :ATTR(:get<ProcessXmlResult>);

__PACKAGE__->_factory(
    [ qw(        ProcessXmlResult

    ) ],
    {
        'ProcessXmlResult' => \%ProcessXmlResult_of,
    },
    {
        'ProcessXmlResult' => 'SOAP::WSDL::XSD::Typelib::Builtin::string',
    },
    {

        'ProcessXmlResult' => 'ProcessXmlResult',
    }
);

} # end BLOCK






} # end of BLOCK



1;


=pod

=head1 NAME

MyElements::ProcessXmlResponse

=head1 DESCRIPTION

Perl data type class for the XML Schema defined element
ProcessXmlResponse from the namespace http://lcs.cz/webservices/.







=head1 PROPERTIES

The following properties may be accessed using get_PROPERTY / set_PROPERTY
methods:

=over

=item * ProcessXmlResult

 $element->set_ProcessXmlResult($data);
 $element->get_ProcessXmlResult();





=back


=head1 METHODS

=head2 new

 my $element = MyElements::ProcessXmlResponse->new($data);

Constructor. The following data structure may be passed to new():

 {
   ProcessXmlResult =>  $some_value, # string
 },

=head1 AUTHOR

Generated by SOAP::WSDL

=cut

