
package Connectors::HeliosConnector::MyElements::ProcessXml;
use strict;
use warnings;

{ # BLOCK to scope variables

sub get_xmlns { 'http://lcs.cz/webservices/' }

__PACKAGE__->__set_name('ProcessXml');
__PACKAGE__->__set_nillable();
__PACKAGE__->__set_minOccurs();
__PACKAGE__->__set_maxOccurs();
__PACKAGE__->__set_ref();

use base qw(
    SOAP::WSDL::XSD::Typelib::Element
    SOAP::WSDL::XSD::Typelib::ComplexType
);

our $XML_ATTRIBUTE_CLASS;
undef $XML_ATTRIBUTE_CLASS;

sub __get_attr_class {
    return $XML_ATTRIBUTE_CLASS;
}

use Class::Std::Fast::Storable constructor => 'none';
use base qw(SOAP::WSDL::XSD::Typelib::ComplexType);

Class::Std::initialize();

{ # BLOCK to scope variables

my %sessionToken_of :ATTR(:get<sessionToken>);
my %inputXml_of :ATTR(:get<inputXml>);

__PACKAGE__->_factory(
    [ qw(        sessionToken
        inputXml

    ) ],
    {
        'sessionToken' => \%sessionToken_of,
        'inputXml' => \%inputXml_of,
    },
    {
        'sessionToken' => 'SOAP::WSDL::XSD::Typelib::Builtin::string',
        'inputXml' => 'SOAP::WSDL::XSD::Typelib::Builtin::string',
    },
    {

        'sessionToken' => 'sessionToken',
        'inputXml' => 'inputXml',
    }
);

} # end BLOCK






} # end of BLOCK



1;


=pod

=head1 NAME

MyElements::ProcessXml

=head1 DESCRIPTION

Perl data type class for the XML Schema defined element
ProcessXml from the namespace http://lcs.cz/webservices/.







=head1 PROPERTIES

The following properties may be accessed using get_PROPERTY / set_PROPERTY
methods:

=over

=item * sessionToken

 $element->set_sessionToken($data);
 $element->get_sessionToken();




=item * inputXml

 $element->set_inputXml($data);
 $element->get_inputXml();





=back


=head1 METHODS

=head2 new

 my $element = MyElements::ProcessXml->new($data);

Constructor. The following data structure may be passed to new():

 {
   sessionToken =>  $some_value, # string
   inputXml =>  $some_value, # string
 },

=head1 AUTHOR

Generated by SOAP::WSDL

=cut

