package Connectors::HeliosConnector::MyInterfaces::Data::DataSoap;
use strict;
use warnings;
use Class::Std::Fast::Storable;
use Scalar::Util qw(blessed);
use base qw(SOAP::WSDL::Client::Base);

# only load if it hasn't been loaded before
require Connectors::HeliosConnector::MyTypemaps::Data
    if not Connectors::HeliosConnector::MyTypemaps::Data->can('get_class');

sub START {
    $_[0]->set_proxy('http://hegsrv.gatema.cz/gatema/data.asmx') if not $_[2]->{proxy};
    $_[0]->set_class_resolver('Connectors::HeliosConnector::MyTypemaps::Data')
        if not $_[2]->{class_resolver};

    $_[0]->set_prefix($_[2]->{use_prefix}) if exists $_[2]->{use_prefix};
}

sub GetInfo {
    my ($self, $body, $header) = @_;
    die "GetInfo must be called as object method (\$self is <$self>)" if not blessed($self);
    return $self->SUPER::call({
        operation => 'GetInfo',
        soap_action => 'http://lcs.cz/webservices/GetInfo',
        style => 'document',
        body => {
            

           'use'            => 'literal',
            namespace       => 'http://schemas.xmlsoap.org/wsdl/soap/',
            encodingStyle   => '',
            parts           =>  [qw( Connectors::HeliosConnector::MyElements::GetInfo )],
        },
        header => {
            
        },
        headerfault => {
            
        }
    }, $body, $header);
}




1;



__END__

=pod

=head1 NAME

MyInterfaces::Data::DataSoap - SOAP Interface for the Data Web Service

=head1 SYNOPSIS

 use MyInterfaces::Data::DataSoap;
 my $interface = MyInterfaces::Data::DataSoap->new();

 my $response;
 $response = $interface->GetInfo();



=head1 DESCRIPTION

SOAP Interface for the Data web service
located at http://heg.gatema.cz/gatema/data.asmx.

=head1 SERVICE Data



=head2 Port DataSoap



=head1 METHODS

=head2 General methods

=head3 new

Constructor.

All arguments are forwarded to L<SOAP::WSDL::Client|SOAP::WSDL::Client>.

=head2 SOAP Service methods

Method synopsis is displayed with hash refs as parameters.

The commented class names in the method's parameters denote that objects
of the corresponding class can be passed instead of the marked hash ref.

You may pass any combination of objects, hash and list refs to these
methods, as long as you meet the structure.

List items (i.e. multiple occurences) are not displayed in the synopsis.
You may generally pass a list ref of hash refs (or objects) instead of a hash
ref - this may result in invalid XML if used improperly, though. Note that
SOAP::WSDL always expects list references at maximum depth position.

XML attributes are not displayed in this synopsis and cannot be set using
hash refs. See the respective class' documentation for additional information.



=head3 GetInfo



Returns a L<MyElements::GetInfoResponse|MyElements::GetInfoResponse> object.

 $response = $interface->GetInfo( {
    myCode =>  $some_value, # string
    myValue =>  $some_value, # string
  },,
 );



=head1 AUTHOR

Generated by SOAP::WSDL on Wed Jul 19 08:12:03 2017

=cut
